name: Latest Blog Posts in Think & Write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update_feed:
    name: Update the list of latest blog posts in README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.2.5
        with:
          feed_list: https://jasonhk.blog/feed/rss2/
          comment_tag_name: FEED:THINK_&_WRITE
          commit_message: Updated with the latest blog posts in Think & Write
          committer_username: think-n-write
          committer_email: think-n-write@jasonhk.email
        
              
